<?php

namespace Database\Seeders;

use App\Models\Kriteria;
use App\Models\ObservasiLokasi;
use App\Models\Periode;
use App\Models\User;
use App\Services\ObservasiService;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ObservasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Mulai melakukan seeding data observasi & TOPSIS terbaru...');

        $user = User::first();
        $userId = $user ? $user->id : 1;

        $kriterias = Kriteria::orderBy('urutan')->get();
        if ($kriterias->count() < 5) {
            $this->command->error('Kriteria kurang dari 5. Pastikan KriteriaSeeder telah dijalankan.');
            return;
        }

        // Ensure Periodes exist
        Periode::firstOrCreate(
            ['id' => 1],
            [
                'nama_periode' => 'Cabang Cianjur 2026',
                'status' => Periode::STATUS_AKTIF,
                'tanggal_mulai' => now()->startOfMonth(),
                'tanggal_selesai' => now()->endOfMonth(),
            ]
        );

        Periode::firstOrCreate(
            ['id' => 2],
            [
                'nama_periode' => 'Cabang Bandung 2026',
                'status' => Periode::STATUS_DIARSIPKAN,
                'tanggal_mulai' => now()->subMonth()->startOfMonth(),
                'tanggal_selesai' => now()->subMonth()->endOfMonth(),
            ]
        );

        $dataset = [
            [
                'id' => 1,
                'periode_id' => 1,
                'user_id' => $userId,
                'nama_pemilik' => 'Bu Ede',
                'nomor_telepon_pemilik' => '081234567890',
                'alamat_lengkap' => 'jl. Perumahan Puncak Manis, Nagrak',
                'provinsi' => 'JAWA BARAT',
                'kabupaten_kota' => 'KABUPATEN CIANJUR',
                'kecamatan' => 'CIANJUR',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203200',
                'latitude' => -6.810866,
                'longitude' => 107.079206,
                'jenis_bangunan' => 'Ruko',
                'kondisi_bangunan' => 'Baik',
                'luas_tanah' => 100.0,
                'luas_bangunan' => 70.0,
                'jumlah_lantai' => 1,
                'jumlah_ruangan' => 2,
                'jumlah_wc' => 1,
                'sumber_air' => 'PDAM',
                'daya_listrik' => '900 VA',
                'area_parkir' => 'Hanya Motor',
                'lebar_jalan' => '< 3 Meter',
                'ventilasi' => 'Baik',
                'sirkulasi' => 'Baik',
                'harga_sewa' => 11400000.0,
                'jarak_rph' => 2.3,
                'nearest_rph_name' => 'pasar domba cianjur',
                'jumlah_kompetitor' => 3,
                'catatan' => NULL,
                'tanggal_observasi' => '2026-07-24',
                'jam_observasi' => '10:00',
                'anggota_pendamping' => array (
  0 => 'Selvi',
),
                'umk' => 3104583.63,
                'pdrb' => 26555.0,
                'jumlah_penduduk_muslim' => 2699003,
                'akses_jalan_utama' => true,
                'akses_kendaraan_operasional' => true,
                'kondisi_jalan_baik' => true,
                'mudah_ditemukan_google_maps' => true,
                'mudah_dijangkau_pelanggan' => true,
                'luas_bangunan_mencukupi' => true,
                'kondisi_bangunan_baik' => false,
                'ventilasi_sirkulasi_memadai' => false,
                'air_listrik_tersedia' => true,
                'area_parkir_memadai' => true,
            ],
            [
                'id' => 2,
                'periode_id' => 1,
                'user_id' => $userId,
                'nama_pemilik' => 'Bu Neng Misri',
                'nomor_telepon_pemilik' => '082345678901',
                'alamat_lengkap' => 'Jl. Sabandar, Sabandar',
                'provinsi' => 'JAWA BARAT',
                'kabupaten_kota' => 'KABUPATEN CIANJUR',
                'kecamatan' => 'KARANGTENGAH',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203190',
                'latitude' => -6.810873,
                'longitude' => 107.079247,
                'jenis_bangunan' => 'Ruko',
                'kondisi_bangunan' => 'Baik',
                'luas_tanah' => 100.0,
                'luas_bangunan' => 100.0,
                'jumlah_lantai' => 1,
                'jumlah_ruangan' => 2,
                'jumlah_wc' => 1,
                'sumber_air' => 'PDAM',
                'daya_listrik' => '2200 VA',
                'area_parkir' => 'Mobil (1-2 Unit)',
                'lebar_jalan' => '< 3 Meter',
                'ventilasi' => 'Baik',
                'sirkulasi' => 'Baik',
                'harga_sewa' => 23000000.0,
                'jarak_rph' => 3.5,
                'nearest_rph_name' => 'RPH teman aqiqah indonesia',
                'jumlah_kompetitor' => 4,
                'catatan' => NULL,
                'tanggal_observasi' => '2026-07-24',
                'jam_observasi' => '10:00',
                'anggota_pendamping' => array (
  0 => 'Fulanah',
),
                'umk' => 3104583.63,
                'pdrb' => 26555.0,
                'jumlah_penduduk_muslim' => 2699003,
                'akses_jalan_utama' => true,
                'akses_kendaraan_operasional' => true,
                'kondisi_jalan_baik' => true,
                'mudah_ditemukan_google_maps' => true,
                'mudah_dijangkau_pelanggan' => true,
                'luas_bangunan_mencukupi' => true,
                'kondisi_bangunan_baik' => true,
                'ventilasi_sirkulasi_memadai' => true,
                'air_listrik_tersedia' => true,
                'area_parkir_memadai' => false,
            ],
            [
                'id' => 3,
                'periode_id' => 1,
                'user_id' => $userId,
                'nama_pemilik' => 'ibu Sarah',
                'nomor_telepon_pemilik' => '083456789012',
                'alamat_lengkap' => 'Jl. Griya Maleber indah',
                'provinsi' => 'JAWA BARAT',
                'kabupaten_kota' => 'KABUPATEN CIANJUR',
                'kecamatan' => 'KARANGTENGAH',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203190',
                'latitude' => -6.810866,
                'longitude' => 107.079208,
                'jenis_bangunan' => 'Ruko',
                'kondisi_bangunan' => 'Baik',
                'luas_tanah' => 100.0,
                'luas_bangunan' => 100.0,
                'jumlah_lantai' => 1,
                'jumlah_ruangan' => 2,
                'jumlah_wc' => 1,
                'sumber_air' => 'PDAM',
                'daya_listrik' => '2200 VA',
                'area_parkir' => 'Mobil (1-2 Unit)',
                'lebar_jalan' => '< 3 Meter',
                'ventilasi' => 'Baik',
                'sirkulasi' => 'Cukup',
                'harga_sewa' => 12000000.0,
                'jarak_rph' => 2.8,
                'nearest_rph_name' => 'RPH Teman Aqiqah Indonesia',
                'jumlah_kompetitor' => 2,
                'catatan' => NULL,
                'tanggal_observasi' => '2026-07-24',
                'jam_observasi' => '10:00',
                'anggota_pendamping' => array (
  0 => 'Selvi',
),
                'umk' => 3104583.63,
                'pdrb' => 26555.0,
                'jumlah_penduduk_muslim' => 2699003,
                'akses_jalan_utama' => true,
                'akses_kendaraan_operasional' => true,
                'kondisi_jalan_baik' => true,
                'mudah_ditemukan_google_maps' => true,
                'mudah_dijangkau_pelanggan' => true,
                'luas_bangunan_mencukupi' => true,
                'kondisi_bangunan_baik' => true,
                'ventilasi_sirkulasi_memadai' => true,
                'air_listrik_tersedia' => false,
                'area_parkir_memadai' => true,
            ],
            [
                'id' => 4,
                'periode_id' => 1,
                'user_id' => $userId,
                'nama_pemilik' => 'Bu Ara',
                'nomor_telepon_pemilik' => '084567890123',
                'alamat_lengkap' => 'Jl. Bumi Emas, Sirnagalih',
                'provinsi' => 'JAWA BARAT',
                'kabupaten_kota' => 'KABUPATEN CIANJUR',
                'kecamatan' => 'CILAKU',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203140',
                'latitude' => -6.8113,
                'longitude' => 107.1381,
                'jenis_bangunan' => 'Ruko',
                'kondisi_bangunan' => 'Baik',
                'luas_tanah' => 70.0,
                'luas_bangunan' => 60.0,
                'jumlah_lantai' => 1,
                'jumlah_ruangan' => 2,
                'jumlah_wc' => 1,
                'sumber_air' => 'PDAM',
                'daya_listrik' => '2200 VA',
                'area_parkir' => 'Mobil (1-2 Unit)',
                'lebar_jalan' => '< 3 Meter',
                'ventilasi' => 'Cukup',
                'sirkulasi' => 'Cukup',
                'harga_sewa' => 12000000.0,
                'jarak_rph' => 1.2,
                'nearest_rph_name' => 'Fathur farm',
                'jumlah_kompetitor' => 2,
                'catatan' => NULL,
                'tanggal_observasi' => '2026-07-24',
                'jam_observasi' => '10:00',
                'anggota_pendamping' => array (
  0 => 'lala',
),
                'umk' => 3104583.63,
                'pdrb' => 26555.0,
                'jumlah_penduduk_muslim' => 2699003,
                'akses_jalan_utama' => true,
                'akses_kendaraan_operasional' => true,
                'kondisi_jalan_baik' => true,
                'mudah_ditemukan_google_maps' => true,
                'mudah_dijangkau_pelanggan' => true,
                'luas_bangunan_mencukupi' => true,
                'kondisi_bangunan_baik' => true,
                'ventilasi_sirkulasi_memadai' => false,
                'air_listrik_tersedia' => true,
                'area_parkir_memadai' => true,
            ],
            [
                'id' => 5,
                'periode_id' => 1,
                'user_id' => $userId,
                'nama_pemilik' => 'Ibu Dewi',
                'nomor_telepon_pemilik' => '085678901234',
                'alamat_lengkap' => 'Jl. Raya Cibeber, Kp Cilaku Kaum',
                'provinsi' => 'JAWA BARAT',
                'kabupaten_kota' => 'KABUPATEN CIANJUR',
                'kecamatan' => 'CILAKU',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203140',
                'latitude' => -6.781319,
                'longitude' => 107.171895,
                'jenis_bangunan' => 'Ruko',
                'kondisi_bangunan' => 'Baik',
                'luas_tanah' => 300.0,
                'luas_bangunan' => 200.0,
                'jumlah_lantai' => 1,
                'jumlah_ruangan' => 6,
                'jumlah_wc' => 2,
                'sumber_air' => 'PDAM',
                'daya_listrik' => '2200 VA',
                'area_parkir' => 'Mobil (1-2 Unit)',
                'lebar_jalan' => '< 3 Meter',
                'ventilasi' => 'Baik',
                'sirkulasi' => 'Baik',
                'harga_sewa' => 16000000.0,
                'jarak_rph' => 1.7,
                'nearest_rph_name' => 'Purwadaksi farm',
                'jumlah_kompetitor' => 2,
                'catatan' => NULL,
                'tanggal_observasi' => '2026-07-24',
                'jam_observasi' => '10:00',
                'anggota_pendamping' => array (
  0 => 'selvi',
  1 => 'lala',
),
                'umk' => 3104583.63,
                'pdrb' => 26555.0,
                'jumlah_penduduk_muslim' => 2699003,
                'akses_jalan_utama' => true,
                'akses_kendaraan_operasional' => true,
                'kondisi_jalan_baik' => true,
                'mudah_ditemukan_google_maps' => false,
                'mudah_dijangkau_pelanggan' => false,
                'luas_bangunan_mencukupi' => true,
                'kondisi_bangunan_baik' => true,
                'ventilasi_sirkulasi_memadai' => true,
                'air_listrik_tersedia' => true,
                'area_parkir_memadai' => false,
            ],
            [
                'id' => 6,
                'periode_id' => 1,
                'user_id' => $userId,
                'nama_pemilik' => 'Pa Asep',
                'nomor_telepon_pemilik' => '086789012345',
                'alamat_lengkap' => 'Jl Saronge,, Ciputri',
                'provinsi' => 'JAWA BARAT',
                'kabupaten_kota' => 'KABUPATEN CIANJUR',
                'kecamatan' => 'PACET',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203220',
                'latitude' => -6.810866,
                'longitude' => 107.079207,
                'jenis_bangunan' => 'Ruko',
                'kondisi_bangunan' => 'Baik',
                'luas_tanah' => 100.0,
                'luas_bangunan' => 100.0,
                'jumlah_lantai' => 1,
                'jumlah_ruangan' => 2,
                'jumlah_wc' => 1,
                'sumber_air' => 'PDAM',
                'daya_listrik' => '2200 VA',
                'area_parkir' => 'Mobil (1-2 Unit)',
                'lebar_jalan' => '< 3 Meter',
                'ventilasi' => 'Baik',
                'sirkulasi' => 'Baik',
                'harga_sewa' => 12000000.0,
                'jarak_rph' => 4.1,
                'nearest_rph_name' => 'Haruko Jaya',
                'jumlah_kompetitor' => 1,
                'catatan' => NULL,
                'tanggal_observasi' => '2026-07-24',
                'jam_observasi' => '10:00',
                'anggota_pendamping' => array (
  0 => 'Selvi',
  1 => 'Lala',
),
                'umk' => 3104583.63,
                'pdrb' => 26555.0,
                'jumlah_penduduk_muslim' => 2699003,
                'akses_jalan_utama' => true,
                'akses_kendaraan_operasional' => false,
                'kondisi_jalan_baik' => false,
                'mudah_ditemukan_google_maps' => false,
                'mudah_dijangkau_pelanggan' => false,
                'luas_bangunan_mencukupi' => true,
                'kondisi_bangunan_baik' => true,
                'ventilasi_sirkulasi_memadai' => true,
                'air_listrik_tersedia' => true,
                'area_parkir_memadai' => true,
            ],
            [
                'id' => 8,
                'periode_id' => 1,
                'user_id' => $userId,
                'nama_pemilik' => 'Bu Ai',
                'nomor_telepon_pemilik' => '08123456789',
                'alamat_lengkap' => 'jl tegal panjang, kp. sarampad RT 01 RW 02',
                'provinsi' => 'JAWA BARAT',
                'kabupaten_kota' => 'KABUPATEN CIANJUR',
                'kecamatan' => 'CUGENANG',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203210',
                'latitude' => -6.810873,
                'longitude' => 107.079247,
                'jenis_bangunan' => NULL,
                'kondisi_bangunan' => 'Baik',
                'luas_tanah' => 120.0,
                'luas_bangunan' => 100.0,
                'jumlah_lantai' => 1,
                'jumlah_ruangan' => 3,
                'jumlah_wc' => 1,
                'sumber_air' => 'PDAM',
                'daya_listrik' => '2200 VA',
                'area_parkir' => 'Mobil (1-2 Unit)',
                'lebar_jalan' => '< 3 Meter',
                'ventilasi' => 'Baik',
                'sirkulasi' => 'Baik',
                'harga_sewa' => 11000000.0,
                'jarak_rph' => 0.37,
                'nearest_rph_name' => 'sentra aqiqah',
                'jumlah_kompetitor' => 1,
                'catatan' => NULL,
                'tanggal_observasi' => '2026-07-24',
                'jam_observasi' => NULL,
                'anggota_pendamping' => NULL,
                'umk' => 3104583.63,
                'pdrb' => 26555.0,
                'jumlah_penduduk_muslim' => 2699003,
                'akses_jalan_utama' => true,
                'akses_kendaraan_operasional' => false,
                'kondisi_jalan_baik' => false,
                'mudah_ditemukan_google_maps' => false,
                'mudah_dijangkau_pelanggan' => false,
                'luas_bangunan_mencukupi' => false,
                'kondisi_bangunan_baik' => true,
                'ventilasi_sirkulasi_memadai' => true,
                'air_listrik_tersedia' => true,
                'area_parkir_memadai' => false,
            ],
            [
                'id' => 9,
                'periode_id' => 2,
                'user_id' => $userId,
                'nama_pemilik' => 'bu nisa',
                'nomor_telepon_pemilik' => '235467',
                'alamat_lengkap' => 'Kecamatan Cianjur, Jawa Barat',
                'provinsi' => 'JAWA BARAT',
                'kabupaten_kota' => 'KABUPATEN CIANJUR',
                'kecamatan' => 'CUGENANG',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203210',
                'latitude' => -6.810865,
                'longitude' => 107.079204,
                'jenis_bangunan' => NULL,
                'kondisi_bangunan' => 'Sangat Baik',
                'luas_tanah' => 120.0,
                'luas_bangunan' => 100.0,
                'jumlah_lantai' => 1,
                'jumlah_ruangan' => 4,
                'jumlah_wc' => 1,
                'sumber_air' => 'PDAM',
                'daya_listrik' => '2200 VA',
                'area_parkir' => 'Mobil (> 2 Unit)',
                'lebar_jalan' => '< 3 Meter',
                'ventilasi' => 'Baik',
                'sirkulasi' => 'Baik',
                'harga_sewa' => 12000000.0,
                'jarak_rph' => 2.0,
                'nearest_rph_name' => 'sentra aqiqah',
                'jumlah_kompetitor' => 2,
                'catatan' => NULL,
                'tanggal_observasi' => '2026-07-24',
                'jam_observasi' => NULL,
                'anggota_pendamping' => NULL,
                'umk' => 3104583.63,
                'pdrb' => 26555.0,
                'jumlah_penduduk_muslim' => 2699003,
                'akses_jalan_utama' => true,
                'akses_kendaraan_operasional' => true,
                'kondisi_jalan_baik' => true,
                'mudah_ditemukan_google_maps' => false,
                'mudah_dijangkau_pelanggan' => false,
                'luas_bangunan_mencukupi' => true,
                'kondisi_bangunan_baik' => true,
                'ventilasi_sirkulasi_memadai' => true,
                'air_listrik_tersedia' => true,
                'area_parkir_memadai' => false,
            ],
            [
                'id' => 10,
                'periode_id' => 2,
                'user_id' => $userId,
                'nama_pemilik' => 'sheli',
                'nomor_telepon_pemilik' => '123456789',
                'alamat_lengkap' => 'jl. tegal panjang, kp. sarampad',
                'provinsi' => 'JAWA BARAT',
                'kabupaten_kota' => 'KABUPATEN CIANJUR',
                'kecamatan' => 'CUGENANG',
                'province_id' => '32',
                'regency_id' => '3203',
                'district_id' => '3203210',
                'latitude' => -6.810866,
                'longitude' => 107.079206,
                'jenis_bangunan' => NULL,
                'kondisi_bangunan' => 'Baik',
                'luas_tanah' => 120.0,
                'luas_bangunan' => 100.0,
                'jumlah_lantai' => 2,
                'jumlah_ruangan' => 5,
                'jumlah_wc' => 1,
                'sumber_air' => 'Sumur Bor',
                'daya_listrik' => '1300 VA',
                'area_parkir' => 'Mobil (1-2 Unit)',
                'lebar_jalan' => '3-5 Meter',
                'ventilasi' => 'Baik',
                'sirkulasi' => 'Baik',
                'harga_sewa' => 11000000.0,
                'jarak_rph' => 0.37,
                'nearest_rph_name' => 'sentra aqiqah',
                'jumlah_kompetitor' => 1,
                'catatan' => NULL,
                'tanggal_observasi' => '2026-07-24',
                'jam_observasi' => NULL,
                'anggota_pendamping' => NULL,
                'umk' => 3104583.63,
                'pdrb' => 26555.0,
                'jumlah_penduduk_muslim' => 2699003,
                'akses_jalan_utama' => true,
                'akses_kendaraan_operasional' => true,
                'kondisi_jalan_baik' => true,
                'mudah_ditemukan_google_maps' => false,
                'mudah_dijangkau_pelanggan' => false,
                'luas_bangunan_mencukupi' => true,
                'kondisi_bangunan_baik' => true,
                'ventilasi_sirkulasi_memadai' => true,
                'air_listrik_tersedia' => true,
                'area_parkir_memadai' => true,
            ],
        ];

        DB::beginTransaction();
        try {
            $observasiService = app(ObservasiService::class);
            foreach ($dataset as $item) {
                $obs = ObservasiLokasi::updateOrCreate(['id' => $item['id']], $item);
                $observasiService->syncPenilaianForObservasi($obs);
            }
            DB::commit();
            $this->command->info('Seeding data observasi & TOPSIS berhasil di-update!');
        } catch (\Exception $e) {
            DB::rollBack();
            $this->command->error('Gagal melakukan seeding: ' . $e->getMessage());
        }
    }
}
